//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurante.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleMenu
    {
        public int IdDetalleMenu { get; set; }
        public int IdMenu { get; set; }
        public int IdPlato { get; set; }
        public int Cantidad { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual Plato Plato { get; set; }
    }
}
