//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurante.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Factura()
        {
            this.DetalleFacturaPlato = new HashSet<DetalleFacturaPlato>();
        }
    
        public int IdFactura { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Estado { get; set; }
        public decimal MontoTotal { get; set; }
        public string Descripcion { get; set; }
        public int IdMesa { get; set; }
        public int IdCliente { get; set; }
        public int IdUsuario { get; set; }
        public int IdTipoDePago { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleFacturaPlato> DetalleFacturaPlato { get; set; }
        public virtual Mesa Mesa { get; set; }
        public virtual MetodoDePago MetodoDePago { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
