//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurante.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plato
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Plato()
        {
            this.DetalleFacturaPlato = new HashSet<DetalleFacturaPlato>();
            this.DetalleMenu = new HashSet<DetalleMenu>();
        }
    
        public int IdPlato { get; set; }
        public string Nombre { get; set; }
        public decimal Precio { get; set; }
        public int IdCategoriaPlato { get; set; }
        public string Descripcion { get; set; }
    
        public virtual CategoriaPlato CategoriaPlato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleFacturaPlato> DetalleFacturaPlato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleMenu> DetalleMenu { get; set; }
    }
}
